## 本稿で得られた知見
### 仮説に対する答え
本稿では、主に2つの問いと仮説を設定し、それらに対する実証分析を行った。仮説0では、先行研究と同じく、SES・学力・教育意識に何らかの関係があることを予想し、第\@ref(model)章にて検証した。結果、本稿で使用したデータセットにおいても、先行研究と同じ関係が確認された。仮説1では、「保護者教育意識の空間は、総量の大きさと志向性の相違によって表現され、より普遍性のある成長を志向した意識と、より希少性のある成長を志向した教育意識に分類される」と予想した。第\@ref(mca)章での分析の結果、保護者の教育意識は仮説で想定したように表現・分類されるものの、総量・分類の軸はいずれも、空間全体に対して大きな説明力を持たない、という知見を得た。仮説2は、「保護者教育意識のうち、普遍性を志向した教育意識よりも、希少性を志向した教育意識の方が、SESによる子どもの学力差を説明する割合が大きい」と予想した。第\@ref(model)章での分析の結果、教育意識の指標を構成する変数によって、結果が一貫しないことが明らかになった。通塾・知育という具体的な行動で構成した場合には、仮説の通り、希少性を志向した教育意識が、普遍性を志向した教育意識よりも、学力格差を説明していた。しかし、第\@ref(mca)章で構築した空間に基づいて構成した場合には、反対に、普遍性を志向した教育意識が、より学力格差を説明していた。いずれの場合においても、それぞれの教育意識が、SESが学力に与える効果に占める割合は、高い方が15%程度、低い方が3%程度であった。

### 理論への還元
仮説1に関する検証からは、保護者・子どもそれぞれの生活空間と同様に、教育意識・養育形式の空間についても、ある程度まで総量と構成の相違で表現できることを確認した。また、仮説2に関する検証からは、ともすれば同じように捉えられてしまう「SESによる養育形式の差」が、養育の目指す意図の相違によって、異なる結果を生むことを確認した。一方で、総量と数点の構成のみで大部分を表現できる空間は、本稿のデータセットからは構築することができなかった。また、構成を示す変数が、単体で学力やその階層差を左右する、という可能性も検討される結果となった。少なくとも、養育形式については、形式同士およびSES・学力との関係について、より慎重に解釈すべきである。

### 実践への適用
本稿の分析結果は、実践への適用について、複雑な判断が必要であることを示唆している。教育機会を増やし、格差を縮小するための政策を立案する上で、最も知りたいことは、誰にどのような資源を提供することで、目的が達成できるか、という点である。ここで、本稿の分析結果が貢献できる点は、ある取り組みが効果的であることと、取り組みの有無・大小が格差の原因であることは、別の問題である、という提起である。近年、幼児教育の効果が注目されているが\citep[135-136]{keikiGakuryokukakusakakudainoshakaigakutekikenkyuShochugakuseienotsuisekitekigakuryokuchosakekkagashimesumono2017}、読み聞かせといった知育それ自体が、学力にプラスの効果をもたらすことは、先行研究や本稿第\@ref(model)章の分析からも、明らかになっている。しかし、第\@ref(model)章の分析結果から、読み聞かせといった取り組みの普及が、学力格差自体を縮小させる、という見通しを持つことは難しい。知育それ自体に効果はあることから、格差縮小が最優先であるならば、不利な社会経済的背景の家庭「だけ」に、取り組みを提供することも、想定されないわけではない。しかし、多くの議論と調整を有することは、論を待たない。

## 課題と展望
### 議論・分析に対する課題
本稿では議論と分析のそれぞれについて、課題が残された。議論に関しては、(1)文化的な要因と、それとは異なる説明の関係性について、十分に検討することができなかった点、(2)文化的な要因に関する説明において、日本における教育制度の特徴と、十分に関連づけることができなかった点が、課題である。分析については、柔軟な分析モデルの設定と、正確な数値測定を両立させることが困難であり、データの分布と推定方法の整合性に課題を残した。

### 教育意識の拡張
より根本的な課題は、学力格差には、本稿で操作化した、保護者の教育意識や家庭の養育形式からは、未だに説明できない要因が想定されるという事実である。今後の研究では、同じように見える保護者の教育に関する行動について、その背後にある意識の相違を、明らかにすることが求められると考える。教育や養育を、究極的には価値観の伝達と捉えるならば、ある程度広く価値観が共有されているような、教育に関する意識だけでなく、より広範な価値観について、解明する必要があると考える。


<!-- 本稿で見られた現象を、さらに深く解明するための手がかりとなりうる概念として、`!cite`ヤングが提唱した「過剰包摂」を取り上げる。過剰包摂が起きている状態とは、ある価値観が広く共有されていながら、その価値観を実現できるのは限られた人のみである、という状態である[55-56]。 -->
