## 本章の目標
本章の目標は、前章で設定した問いに対応する、仮説・リサーチデザイン・測定概念を設定することである。

## 仮説
理論仮説は以下の通りである。

- 仮説0a: SESが高いほど子どもの学力は高い。
- 仮説0b: SESが高いほど保護者の教育意識は高い。
- 仮説0c: 保護者の教育意識が高いほど子どもの学力は高い。
- 仮説0d: SESによる子どもの学力差は、教育意識によって、部分的に媒介される。
- 仮説1a: 保護者教育意識の空間は、総量の大きさと志向性の相違によって表現される。
- 仮説1b: 保護者教育意識は、より普遍性のある成長を志向した意識と、より希少性のある成長を志向した教育意識に分類される。
- 仮説2: 保護者教育意識のうち、普遍性を志向した教育意識よりも、希少性を志向した教育意識の方が、SESによる子どもの学力差を説明する割合が大きい。

仮説0aは\citet{toshiakiTokeiHenNippon2019}、仮説0bは\citet{ryojiKyoikuKakusa2019}、仮設0cは\citet{wataruGakkobunkatokyoikukakusaNipponshakainibunkashihongainenodotekiyosuruka2022}、仮設0dは\citet{parkHomeLiteracyEnvironments2008}、といった研究から、仮説の妥当性が明らかにされている。本稿では、異なるデータセットおよび地域であっても、パターンが同様であることを確認するために、仮説0aから仮説0dの検証を行う。仮説1はRQ1に、仮説2はRQ2に対応した仮説である。仮説は、前章で議論した、\citet{wataruGakkobunkatokyoikukakusaNipponshakainibunkashihongainenodotekiyosuruka2022}による小学生の生活様式空間と、SES・学力との関連に関する研究から、着想を得た。保護者の教育意識についても、子どもの意識・行動と同じく、2つに分化すると考える。1つは、学校の試験や入試において、高い成績を収めることを志向した、意識や行動である。究極的には、他の人にない知識や技術を有することで、学校や企業に評価されることを目指す意識・行動であるので、これを「希少性志向」とする。もう1つの教育意識については、希少性の反対であると想定し、これを「普遍性志向」とする。

## リサーチデザイン
本稿では、児童の学力・社会経済的背景・家庭環境に関する量的データを取得し、仮説検証のための計量分析を行う。データは「IEA国際数学・理科教育動向調査(TIMSS) 2015年調査」を使用し、日本国内の小学4年生の児童とその保護者を対象とした分析を行う。仮説1に対しては、質的変数の分類手法である多重対応分析を行い、教育意識に関する空間を構築する。仮説2に対しては、構造方程式によるモデルを設定し、方程式の係数を推定することで、SESが学力に与える総合的な効果と、それぞれの教育意識を経由した間接的な効果の大きさを推定する。

## 測定・操作化
### SES
本稿ではSESを保護者の学歴と定義する。
SES(社会経済的地位)は、一般的に、「経済的、文化的、社会的要素を統合した地位」\citep[81]{ryojiKyoikuKakusa2019}を指す。保護者学歴をSESとして採用することで、教育格差全般を論じた\citet{ryojiKyoikuKakusa2019}、学力格差の推移を分析した\citet{keikiGakuryokukakusakakudainoshakaigakutekikenkyuShochugakuseienotsuisekitekigakuryokuchosakekkagashimesumono2017}といった先行研究との比較可能性を確保する。
なお、階層研究では、職業地位を階層の代理指標としてきた。\citep[73-74]{kazushiKakusanoshakaigakunyumon2014}。
\citet{hiroyukiShakaikukantogakuryokunokaisosa2012}に基づくならば、学歴と職業地位が、学力に対し、それぞれ異なる作用を持つ可能性は低い。本稿では、学歴は再利用が可能な「シンボリック・トークン(象徴的通標)」\citep[241]{toruGendaiNipponNo2014}としての役割が高まっていることも踏まえ、SESの指標として学歴を使用する。

### 学力
学力は主に「カリキュラムをどの程度習得しているか」という観点から設定する。本稿で使用するIEA国際数学・理科教育動向調査(TIMSS)は、各教科における指導内容の定着度を測定するものである\citep[108]{toshiakiTokeiHenNippon2019}。学力には他にも、「実生活でどの程度活用ができるか」という観点もある。一例として、OECD生徒の学習到達度調査(PISA)は、「それまでに身に付けてきた知識や技能を，実生活の様々な場面で直面する課題にどの程度活用できるかを測る」\citep{kokuritsukyoikuseisakukenkyujoOECDseitonogakushutotatsudochosa2022nenchosaPanfuretton.d.}ことが目的である。いずれにせよ、SESに基づく学力格差は、直接比較は困難であるものの、TIMSSおよびPISAの双方において確認される\citep[113-121]{toshiakiTokeiHenNippon2019}。よって、どちらの観点から定義された学力であっても、本稿の分析目的は達成することが可能である。学力調査と測定学力の関係については、後ほど説明する。

### 教育意識
教育意識は、実際に保護者が行った行動から測定する。また、多重対応分析によって構築された教育意識の空間から、新たな教育意識の分類を定義する。

## 小括
本章では、本章の目標は、前章で設定した問いに対応する、仮説・リサーチデザイン・測定概念を設定した。今後の章では、TIMSS2015データを使用し、量的分析によって、仮説を検証する。
