## 本章の目標
本章の目標は、分析に使用する「IEA国際数学・理科教育動向調査(TIMSS) 2015年調査」の特徴を確認することである。調査概要のほか、分析で留意する点について記載する。

## 使用データ
### データの概要
- 調査名: IEA国際数学・理科教育動向調査(TIMSS) 2015年調査
- 調査対象: 日本国内の小学校に通う小学4年生
- 抽出方法: 1)人口などで層化の上、小学校を150程度抽出 2)抽出した各小学校の中から1学級を抽出
- 参加人数: 148校・約4700人
- 調査項目:
    - 算数および理科の到達度評価
    - 質問紙調査(児童および保護者・学校・教師)


本稿では、データセットとして、国際教育到達度評価学会(IEA)が実施した「IEA国際数学・理科教育動向調査(TIMSS) 2015年調査」を使用する。分析対象は、日本国内の小学校に通う小学4年生の児童とその保護者である。TIMSSの調査対象者は、層化二段抽出法によって抽出される。具体的には、まず第1段階として、人口などで層化の上、小学校を150程度抽出する。次に、抽出した各小学校の中から1学級を抽出する。2015年調査の参加校数は148校、参加児童数は約4700人である。調査では、算数および理科の到達度評価試験と、児童および保護者・学校・教師を対象とした質問紙調査が実施される\citep{kokuritsukyoikuseisakukenkyujoTIMSS2015sansuSugakukyoikuRikakyoikunokokusaihikaku2017}。

### データの限界
TIMSSは学力だけでなく、児童の社会経済的背景についても、質問紙調査を実施する。そのため、保護者の学歴や職業といった情報から、SESと学力の関係について、ある程度分析を行うことが可能である。一方で、家族構成といった、より詳細な背景については設問にないため、関連の分析や統制を行うことができない点に、留意する必要がある。

## 分析の留意点
以下の分析にあたっては、R言語のパッケージである`EdSurvey`パッケージ、`BIFIEsurvey`パッケージ等を使用する。

### 統計量の推定方法
標本調査では、対象となる集団に属する個人について、標本として選ばれる確率が全員等しいことが望ましい。しかし、実際には、地域や個人の属性によって、標本に選ばれる確率が異なることがあり得る。また、標本として選ばれたものの、何らかの事情で調査に参加できないということも想定される。このような場合に発生する誤差を、ウェイトによって補正する必要がある\citep[85-95]{akiraPISAchosanokaiboNoryokuhyokaChosanomoderu2019}。TIMSSでは、標本調査による誤差を補正するウェイトが用意されており、本稿の分析ではこれを用いて推定を行う\citep[3.21-3.22]{larocheSampleDesignTIMSS2016}。

### 標本誤差の算出方法
TIMSSは多段層化抽出法によってサンプリングされる。そのため、統計量の推定にあたり、単純無作為抽出を想定した誤差に加え、多段層化抽出による誤差も考慮する必要がある\citep[104-112]{akiraPISAchosanokaiboNoryokuhyokaChosanomoderu2019}。TIMSSは、多段層化抽出による誤差を、ジャックナイフ法に基づく複製ウェイトによって補正している\citep[4.1-4.6]{foyEstimatingStandardErrors2016}。本稿の分析では、極力複製ウェイトを考慮した推定を行う。

### テストスコアの推定方法
TIMSSにおいてテストスコアは、児童1人につき1つのスコアではなく、5つのスコア推定値が与えられる。これらの推定値は"Plausible Values(PVs)"と呼ばれる。TIMSSでは到達度を測定する際、児童にはそれぞれ異なる一部の問題のみが出題される。統計量を推定する際は、5つのPVそれぞれについて推定量と標準誤差を算出し、統合する\citep[13.2-13.26]{foyScalingTIMSS20152016}。本稿の分析では、極力PVsを考慮した推定を行う。

## 小括
本章では、学力調査であるTIMSSについて、目的や特徴を確認した。次章以降では、TIMSSデータを分析し、仮説について検討する。
